# Generated by Django 5.0.2 on 2024-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yt_video',
            name='length',
            field=models.IntegerField(),
        ),
    ]
